### ISSUE TITLE
Cannot access DeeplayModule attributes inside DeeplayModules

### ISSUE THREAD

**Issue by Henrik-KM** [DeepTrackAI/deeplay#41] opened 2023-12-18 08:55 UTC
It is not possible to configure the layers of a DeeplayModule inside the class definition of another DeeplayModule, i.e. this works in general:

```
rnn = RecurrentNeuralNetwork(in_features=10,hidden_features=[20,30,40],out_features=50)
rnn.blocks.layer.configure(torch.nn.LSTM)
```

But this does not:

```
class RNNModel(DeeplayModule):
    def __init__(self):
        super().__init__()
        rnn=RecurrentNeuralNetwork(in_features=10,hidden_features=[20,30,40],out_features=50)
        rnn.blocks.layer.configure(torch.nn.LSTM)
```

No properties or attributes of the internal DeeplayModule, i.e. blocks, layers, etc, can be accessed.

**Comment by JesusPinedaC** [comment] 2023-12-18 15:58
I can reproduce the issue!

**Comment by BenjaminMidtvedt** [comment] 2023-12-18 16:03
@Henrik-KM Ok. If you first assign it to the module? so
```py
self.rnn = ...
self.rnn.blocks.layer.configure(...)
```

**Comment by BenjaminMidtvedt** [comment] 2023-12-18 16:34
The reason for this is a bit complex. But basically, `rnn` doesn't get created fully until it receives a configuration. It receives this from the parent on assignment. The reason was basically to avoid a lot of superfluous constructor calls. 

We can easily remove this by removing two lines in the metaclass. It would not change how any existing code works, but could lead to large nested models being slower to create.

**Comment by Henrik-KM** [comment] 2023-12-18 16:54
Ah ok, we suspected it was related to that. Well, it works as you wrote above, so I think we can close this issue and keep it in mind!

**Closed as completed** 2023-12-18 17:01 UTC
